name: Generate shadowrocket rules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build_rules_list:
    runs-on: ubuntu-latest
    steps:
      - name: Generate geosite_category-ads-all.list file
        run: |
          curl -sSL https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.list \
          | sed -E 's/^\+\./DOMAIN-SUFFIX,/; s/^[^D]/DOMAIN-SUFFIX,&/' > geosite_category-ads-all.list
          
      - name: Generate geosite_gfw.list file
        run: |
          curl -sSL https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.list \
          | sed -E 's/^\+\./DOMAIN-SUFFIX,/; s/^[^D]/DOMAIN-SUFFIX,&/' > geosite_gfw.list

      - name: Generate geosite_private.list file
        run: |
          curl -sSL https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.list \
          | sed -E 's/^\+\./DOMAIN-SUFFIX,/; s/^[^D]/DOMAIN-SUFFIX,&/' > geosite_private.list

      - name: Generate geosite_cn.list file
        run: |
          curl -sSL https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.list \
          | sed -E 's/^\+\./DOMAIN-SUFFIX,/; s/^[^D]/DOMAIN-SUFFIX,&/' > geosite_cn.list


      - name: Generate geoip_telegram.list file
        run: |
          curl -sSL https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.list | sed 's/^/IP-CIDR,/' > geoip_telegram.list

      - name: Generate geoip_private.list file
        run: |
          curl -sSL https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.list | sed 's/^/IP-CIDR,/' > geoip_private.list

      - name: Generate geoip_cn.list file
        run: |
          curl -sSL https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.list | sed 's/^/IP-CIDR,/' > geoip_cn.list         

      - name: Move files to rules directory
        run: |
          mkdir -p rules.d
          cp *.list ./rules.d/

      - name: Upload rule list artifact
        uses: actions/upload-artifact@v4
        with:
          name: rules
          path: ./rules.d/

  build_Shadowrocket_conf_file:
    runs-on: ubuntu-latest
    needs: build_rules_list
    steps:
      - name: Creating Folders
        run: |
          mkdir -p conf.d
          
      - name: Get common configuration files
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: 'Custom'
          token: ${{ secrets.ACCESS_TOKEN }}
          sparse-checkout: |
            General.txt
          sparse-checkout-cone-mode: false
          path: conf.d

      - name: Concatenate rule configuration files
        run: |
          cat <<EOF >> ./conf.d/General.txt
          [Rule]
          RULE-SET,https://raw.githubusercontent.com/loong-chen-88/Useful-Rules/release/rules/geosite_category-ads-all.list,REJECT
          RULE-SET,https://raw.githubusercontent.com/loong-chen-88/Useful-Rules/release/rules/geosite_gfw.list,PROXY
          RULE-SET,https://raw.githubusercontent.com/loong-chen-88/Useful-Rules/release/rules/geosite_private.list,DIRECT
          RULE-SET,https://raw.githubusercontent.com/loong-chen-88/Useful-Rules/release/rules/geosite_cn.list,DIRECT
          
          RULE-SET,https://raw.githubusercontent.com/loong-chen-88/Useful-Rules/release/rules/geoip_telegram.list,PROXY,no-resolve
          RULE-SET,https://raw.githubusercontent.com/loong-chen-88/Useful-Rules/release/rules/geoip_private.list,DIRECT,no-resolve
          RULE-SET,https://raw.githubusercontent.com/loong-chen-88/Useful-Rules/release/rules/geoip_cn.list,DIRECT,no-resolve
          FINAL,PROXY
          
          EOF

      - name: Generate URL rewrite configuration file
        run: |
          curl -sSL https://raw.githubusercontent.com/Semporia/TikTok-Unlock/master/Shadowrocket/TiKTok-US.conf | sed -n '/\[URL Rewrite\]/,$p' > URL_Rewrite.txt
          sed -i '/\[MITM\]/,$d' URL_Rewrite.txt
          sed -i '/\[URL Rewrite\]/a\^https?://(www.)?g.cn https://www.google.com 302\n^https?://(www.)?google.cn https://www.google.com 302' URL_Rewrite.txt
          cp URL_Rewrite.txt ./conf.d

      - name: Generate HTTPS decrypted configuration file
        run: |
          curl -sSL https://raw.githubusercontent.com/Semporia/TikTok-Unlock/master/Shadowrocket/TiKTok-US.conf | sed -n '/\[MITM\]/,$p' > MITM.txt
          sed -i 's/hostname = /hostname = *snssdk.com,*amemv.com,*instagram.com,/' MITM.txt
          cp MITM.txt ./conf.d

      - name: Concatenate All configuration file
        run: |
          cat ./conf.d/*.txt > ./conf.d/Shadowrocket.conf
          sed -i "1s/^/# Built on $(TZ="Asia/Shanghai" date)\n/" ./conf.d/Shadowrocket.conf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: conf
          path: ./conf.d/Shadowrocket.conf
          retention-days: 5

  publish:
    runs-on: ubuntu-latest
    needs: [build_rules_list,build_Shadowrocket_conf_file]
    steps:     
      - name: Configure variable names
        run: |
          echo "RELEASE_NAME=Built on $(TZ="Asia/Shanghai" date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(TZ="Asia/Shanghai" date +%Y%m%d%H%M)" >> $GITHUB_ENV
          mkdir -p rules

      - name: Download artifact 
        uses: actions/download-artifact@v4
        with:
          path: ./rules

      - name: Publish and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./rules/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload artifact to "release" branch
        run: |
          cd rules || exit 1
          git init
          git config --local user.name ${{ secrets.USER_NAME }}
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
          # git push --delete origin $( git ls-remote --tags origin | awk '{print $2}' | grep -vE "$(echo -e ${TAG_NAME})")
          
      - name: Purge jsdelivr CDN
        run: |
          cd rules || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done

  Delete_Historical_Data:
    runs-on: ubuntu-latest
    needs: publish
    steps:
        - name: Delete old artifacts
          uses: geekyeggo/delete-artifact@v5
          with:
            name: rules

        - name: Delete old tags and releases
          uses: dev-drprasad/delete-older-releases@v0.3.3
          with:
            keep_latest: 7
            delete_tags: true
          env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        - name: Delete old workflow runs
          uses: Mattraks/delete-workflow-runs@v2
          with:
            token: ${{ secrets.ACCESS_TOKEN }}
            repository: ${{ github.repository }}
            retain_days: 30
            keep_minimum_runs: 6
          
    
