name: Delete Tags

on:
  push:
    branches:
      - main

jobs:
  delete_tags:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Tags
      run: git tag -l | grep '^2023' > tagsToDelete.txt

    - name: Delete Tags
      run: |
        while IFS= read -r tag; do
          git tag -d "$tag"
          git push origin ":refs/tags/$tag"
        done < tagsToDelete.txt

    - name: Clean Up
      run: rm tagsToDelete.txt
